# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/hardkernel/odroidxu/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/srp_cga.bin:system/vendor/firmware/srp_cga.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/srp_data.bin:system/vendor/firmware/srp_data.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/srp_vliw.bin:system/vendor/firmware/srp_vliw.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so:system/vendor/lib/egl/libEGL_POWERVR_SGX544_115.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/liboclcompiler.so:system/vendor/lib/liboclcompiler.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libPVROCL.so:system/vendor/lib/libPVROCL.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libusc.so:system/vendor/lib/libusc.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/bin/pvrsrvctl:system/vendor/bin/pvrsrvctl \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/hw/gralloc.exynos5.so:system/vendor/lib/hw/gralloc.exynos5.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/fimc_is_gumi_fw2.bin:system/vendor/firmware/fimc_is_gumi_fw2.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/fimc_is_sec_fw2.bin:system/vendor/firmware/fimc_is_sec_fw2.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/setfile_gumi_imx135.bin:system/vendor/firmware/setfile_gumi_imx135.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/firmware/setfile_sec_imx135.bin:system/vendor/firmware/setfile_sec_imx135.bin \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/liblvverx_3.18.11.so:system/vendor/lib/liblvverx_3.18.11.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/liblvvetx_3.18.11.so:system/vendor/lib/liblvvetx_3.18.11.so \
    vendor/hardkernel/odroidxu/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so
